### ISSUE TITLE
The starter app will not build in Azure Static Web Apps

### ISSUE THREAD

**Issue by nealrobben** [ColdStart-Challenge/ColdStart-Challenge-2021#1]
I have added the starter app to a repo and tried to deply to Azure Static Web Apps.
However, I get a 404 error during the build:

Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node"

**Comment by nealrobben** [comment]
I have managed to get past this error by updating the package in package.json to version 4.14.1 but then I just get another error:

ERROR  Failed to compile with 1 errors10:18:50 PM

 error  in ./src/store/index.js

Module Error (from ./node_modules/eslint-loader/index.js):

/github/workspace/vue-app/src/store/index.js
  5:15  error  No named exports found in module './modules/mutation-types'  import/export

**Comment by ntrogh** [comment]
@nealrobben Thanks for reporting. We've updated the starter application and should work now!

**Comment by bartbilliet** [comment]
Whoops - Ignore the reference, I didn't take care in naming the commit message on my fork it seems. I already [amended the commit message, but apparently, the reference stays forever](https://github.com/isaacs/github/issues/1081)...
