### ISSUE TITLE
[CHALLENGE SUBMISSION]

### ISSUE THREAD

**Issue by groovy-sky** [ColdStart-Challenge/ColdStart-Challenge-2021#14]
Please provide the following information for your submission:

What is your name (First, Last): Jurijs Fadejevs

Where is your GitHub Repo (with your challenge solution): https://github.com/groovy-sky/ColdStart

What Challenge is this for (challenge number between 1 and 6): 1

(Optional) Anything else we should know? e.g., language used, location, blog post? Running result - https://ashy-grass-0dbba0c03.azurestaticapps.net

**Comment by ntrogh** [comment]
Thanks for participating in our coding challenges ❤! To claim your Raspberry PI device, please DM me on Twitter to get the link for providing your shipping details. https://twitter.com/nicktrog

**Comment by groovy-sky** [comment]
Thank you. Done.
