### ISSUE TITLE
[Bug] Settings file name in api project

### ISSUE THREAD

**Issue by neighbourlittle** [ColdStart-Challenge/ColdStart-Challenge-2021#15]
In Challenge 1 starter.

Setting file in api project is named local.setting.json instead of local.setting**s**.json 
When running localy functions expect this file to be named local.settings.json, lookup for connections will warn if you leave it as is.

[https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-output?tabs=javascript#configuration](url)

**Comment by ntrogh** [comment]
Agree, clarified it in the Getting Started document. We're excluding the local.setttings.json file in .gitignore not to persist secrets in the GitHub repo. Thanks for pointing this out! 🙏
