### ISSUE TITLE
Question: Challenge2

### ISSUE THREAD

**Issue by BenjaminVandenBroeck** [ColdStart-Challenge/ColdStart-Challenge-2021#21]
Hi,

Challenge 2 seems pretty straight forward, though I still have some questions:
- We don't have to do anything with the preorders in our storage queue we created in challenge 1? Can we delete this queue if no longer needed?
- Basically for the personalizer, there needs to be a "Recommended" card shown that shows the ice-cream the personalizer recommends us. and below that we should still show the entire list incase the user wants something different correct?

**Comment by ntrogh** [comment]
Hi @brutalsatyr. You will need be needing the queue in challenge 3, when they will be processed by the backend systems.
About the recommendation, yes that's the idea. Show a recommendation alongside/above the list of products.
