### ISSUE TITLE
Challenge 4 - Objective 2: Missing Blazor starter app

### ISSUE THREAD

**Issue by sujithq** [ColdStart-Challenge/ColdStart-Challenge-2021#49]
I think we are missing the blazor starter app for Challenge 4 - Objective 2

**Comment by bartbilliet** [comment]
The Blazor app [seems added now](https://github.com/ColdStart-Challenge/ColdStart-Challenge-2021/tree/main/challenges/challenge4/starter/ColdStartCustomerSWA), although I think the upload missed the referenced **ColdStartComponents** project? 

https://github.com/ColdStart-Challenge/ColdStart-Challenge-2021/blob/fbf904bd4e7606bf6f8e4c84768ce33044ec90ef/challenges/challenge4/starter/ColdStartCustomerSWA/ColdStartCustomerSWA/ColdStartCustomerSWA.csproj#L18
https://github.com/ColdStart-Challenge/ColdStart-Challenge-2021/blob/fbf904bd4e7606bf6f8e4c84768ce33044ec90ef/challenges/challenge4/starter/ColdStartCustomerSWA/ColdStartCustomerSWA/_Imports.razor#L14

I would believe this project would hold the TemplatedList component which I seem to be missing. (Only reference I find to this component is [here](https://github.com/dotnet-presentations/blazor-workshop/blob/master/src/BlazingComponents/TemplatedList.razor))
