### ISSUE TITLE
Azure functions return error

### ISSUE THREAD

**Issue by nealrobben** [ColdStart-Challenge/ColdStart-Challenge-2021#51]
I have deployed the azure functions from the starter solution to a new function app.
However, if I try to call any of these functions from the browser I get the following exception.
I copied the function url from azure itself so I know that is correct.
What could be causing this exception?

{
  "input": "undefined",
  "code": "ERR_INVALID_URL"
}

**Comment by bartbilliet** [comment]
It works for me, but I have deployed them to the existing Azure Function app which we created for the timer & queue trigger in challenge 3. Find my sample here: 
- API: https://github.com/bartbilliet/ColdStart-Challenge-2021/tree/main/challenges/challenge4/completed/coldstartapi
- Github actions workflow which I use to deploy it to an Azure Function app: https://github.com/bartbilliet/ColdStart-Challenge-2021/blob/main/.github/workflows/azure-static-web-apps-calm-forest-037926d03.yml

(I also implemented the drivers API there btw, given your question in #50)

**Comment by nealrobben** [comment]
I have created a new functions app and deployed them via visual studio code.
Tomorrow I will check whether I have configured the correct values for connection to my database etc....

So we are supposed to implement the drivers api ourselves?
I was not sure of that since it is not explicitly mentioned in the instructions.

**Comment by nealrobben** [comment]
It appears I had misconfigured my CosmosDB connection.
